### ISSUE TITLE
This app need to be updated

### ISSUE THREAD

**Issue by ljq8896** [tarassh/eos-ledger#14]
Ledger had released a new firmware 1.6.0 for nano S which solved signing transactions with Windows version 1903 and above. It also have new UI design. BTC, ETH, FIDO U2F and some other apps had been up to date with the firmware. But eos-app didn't update for a while. It still can't sign transactions with new Windows OS. Is there a plan to update it or will eos community give up the support?

**Comment by tarassh** [comment]
https://github.com/LedgerHQ/app-eos/pull/5
