### ISSUE TITLE
Questions about RFC6979 implementation

### ISSUE THREAD

**Issue by emilyofearth** [tarassh/eos-ledger#2]
Out of curiosity, why was it necessary to use a custom RFC6979 implementation?  The RFC6979 algorithm is supposed to be deterministic, so if there is another implementation that doesn't agree, isn't one or the other actually wrong?

I also noticed the loop termination condition seems to be incorrect.  It does not reject an all-zero nonce, and it also will accept a nonce greater than or equal to `n` if any of its octets is less than the corresponding octet of `n` (even if a preceding octet was larger, making `T > n`), creating a statistical bias.  For example, it would accept `V` equal to `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00`.  The bias should be pretty small because of the large number of leading bits of `n`, but it would still be better if there were no bias.

**Comment by tarassh** [comment]
The reason for implementing custom RFC6979 is that EOS and graphene blockchains has its own definition of canonical signatures.
Firmware implementation of RFC satisfies canonical criteria from time to time.
