### ISSUE TITLE
Please merge my code with yours to support new features

### ISSUE THREAD

**Issue by altShiftDev** [tarassh/eos-ledger#3]
Hi tarassh,

My ledger device code supports more features including multi-action transactions (createAccount) and arbitrary transaction signing (sign tx hash). Please use this as a guide to implement these features in your code and get them on the official ledger EOS app. I'd also recommend switching to my app icon, it looks closer to the real EOS icon in my opinion.

I'd also like to get support for updateauth transaction structure signing, while my code doesn't support this right now it should be trivial to do so.

Repo:
https://github.com/altShiftDev/ledger-app-eos

**Comment by tarassh** [comment]
Good, will look into it.

Thank you.
